import { createStitches } from "@stitches/react";
import type { CSS as StitchesCSS, PropertyValue } from "@stitches/react";
import {
  sage,
  red,
  blue,
  green,
  yellow,
  sageA,
  redA,
  blueA,
  greenA,
  yellowA,
  whiteA,
  blackA,
  sageDark,
  redDark,
  blueDark,
  greenDark,
  yellowDark,
  sageDarkA,
  redDarkA,
  blueDarkA,
  greenDarkA,
  yellowDarkA,
} from "@radix-ui/colors";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    // Learn How To Compose Palette :https://www.radix-ui.com/docs/colors/palette-composition/composing-a-palette
    colors: {
      // Brand Scale: https://www.radix-ui.com/docs/colors/palette-composition/composing-a-palette#choosing-a-brand-scale
      // these all need to be typed out for enhanced TS typing
      primary1: green.green1,
      primary2: green.green2,
      primary3: green.green3,
      primary4: green.green4,
      primary5: green.green5,
      primary6: green.green6,
      primary7: green.green7,
      primary8: green.green8,
      primary9: green.green9,
      primary10: green.green10,
      primary11: green.green11,
      primary12: green.green12,

      primaryA1: greenA.greenA1,
      primaryA2: greenA.greenA2,
      primaryA3: greenA.greenA3,
      primaryA4: greenA.greenA4,
      primaryA5: greenA.greenA5,
      primaryA6: greenA.greenA6,
      primaryA7: greenA.greenA7,
      primaryA8: greenA.greenA8,
      primaryA9: greenA.greenA9,
      primaryA10: greenA.greenA10,
      primaryA11: greenA.greenA11,
      primaryA12: greenA.greenA12,

      secondary1: blue.blue1,
      secondary2: blue.blue2,
      secondary3: blue.blue3,
      secondary4: blue.blue4,
      secondary5: blue.blue5,
      secondary6: blue.blue6,
      secondary7: blue.blue7,
      secondary8: blue.blue8,
      secondary9: blue.blue9,
      secondary10: blue.blue10,
      secondary11: blue.blue11,
      secondary12: blue.blue12,

      secondaryA1: blueA.blueA1,
      secondaryA2: blueA.blueA2,
      secondaryA3: blueA.blueA3,
      secondaryA4: blueA.blueA4,
      secondaryA5: blueA.blueA5,
      secondaryA6: blueA.blueA6,
      secondaryA7: blueA.blueA7,
      secondaryA8: blueA.blueA8,
      secondaryA9: blueA.blueA9,
      secondaryA10: blueA.blueA10,
      secondaryA11: blueA.blueA11,
      secondaryA12: blueA.blueA12,

      // Gray Scale: https://www.radix-ui.com/docs/colors/palette-composition/composing-a-palette#choosing-a-gray-scale
      gray1: sage.sage1,
      gray2: sage.sage2,
      gray3: sage.sage3,
      gray4: sage.sage4,
      gray5: sage.sage5,
      gray6: sage.sage6,
      gray7: sage.sage7,
      gray8: sage.sage8,
      gray9: sage.sage9,
      gray10: sage.sage10,
      gray11: sage.sage11,
      gray12: sage.sage12,

      grayA1: sageA.sageA1,
      grayA2: sageA.sageA2,
      grayA3: sageA.sageA3,
      grayA4: sageA.sageA4,
      grayA5: sageA.sageA5,
      grayA6: sageA.sageA6,
      grayA7: sageA.sageA7,
      grayA8: sageA.sageA8,
      grayA9: sageA.sageA9,
      grayA10: sageA.sageA10,
      grayA11: sageA.sageA11,
      grayA12: sageA.sageA12,

      // Semantic Scales: https://www.radix-ui.com/docs/colors/palette-composition/composing-a-palette#choosing-semantic-scales
      success1: green.green1,
      success2: green.green2,
      success3: green.green3,
      success4: green.green4,
      success5: green.green5,
      success6: green.green6,
      success7: green.green7,
      success8: green.green8,
      success9: green.green9,
      success10: green.green10,
      success11: green.green11,
      success12: green.green12,

      successA1: greenA.greenA1,
      successA2: greenA.greenA2,
      successA3: greenA.greenA3,
      successA4: greenA.greenA4,
      successA5: greenA.greenA5,
      successA6: greenA.greenA6,
      successA7: greenA.greenA7,
      successA8: greenA.greenA8,
      successA9: greenA.greenA9,
      successA10: greenA.greenA10,
      successA11: greenA.greenA11,
      successA12: greenA.greenA12,

      info1: blue.blue1,
      info2: blue.blue2,
      info3: blue.blue3,
      info4: blue.blue4,
      info5: blue.blue5,
      info6: blue.blue6,
      info7: blue.blue7,
      info8: blue.blue8,
      info9: blue.blue9,
      info10: blue.blue10,
      info11: blue.blue11,
      info12: blue.blue12,

      infoA1: blueA.blueA1,
      infoA2: blueA.blueA2,
      infoA3: blueA.blueA3,
      infoA4: blueA.blueA4,
      infoA5: blueA.blueA5,
      infoA6: blueA.blueA6,
      infoA7: blueA.blueA7,
      infoA8: blueA.blueA8,
      infoA9: blueA.blueA9,
      infoA10: blueA.blueA10,
      infoA11: blueA.blueA11,
      infoA12: blueA.blueA12,

      warn1: yellow.yellow1,
      warn2: yellow.yellow2,
      warn3: yellow.yellow3,
      warn4: yellow.yellow4,
      warn5: yellow.yellow5,
      warn6: yellow.yellow6,
      warn7: yellow.yellow7,
      warn8: yellow.yellow8,
      warn9: yellow.yellow9,
      warn10: yellow.yellow10,
      warn11: yellow.yellow11,
      warn12: yellow.yellow12,

      warnA1: yellowA.yellowA1,
      warnA2: yellowA.yellowA2,
      warnA3: yellowA.yellowA3,
      warnA4: yellowA.yellowA4,
      warnA5: yellowA.yellowA5,
      warnA6: yellowA.yellowA6,
      warnA7: yellowA.yellowA7,
      warnA8: yellowA.yellowA8,
      warnA9: yellowA.yellowA9,
      warnA10: yellowA.yellowA10,
      warnA11: yellowA.yellowA11,
      warnA12: yellowA.yellowA12,

      error1: red.red1,
      error2: red.red2,
      error3: red.red3,
      error4: red.red4,
      error5: red.red5,
      error6: red.red6,
      error7: red.red7,
      error8: red.red8,
      error9: red.red9,
      error10: red.red10,
      error11: red.red11,
      error12: red.red12,

      errorA1: redA.redA1,
      errorA2: redA.redA2,
      errorA3: redA.redA3,
      errorA4: redA.redA4,
      errorA5: redA.redA5,
      errorA6: redA.redA6,
      errorA7: redA.redA7,
      errorA8: redA.redA8,
      errorA9: redA.redA9,
      errorA10: redA.redA10,
      errorA11: redA.redA11,
      errorA12: redA.redA12,

      // Overlays: https://www.radix-ui.com/docs/colors/palette-composition/the-scales#overlays
      ...whiteA,
      ...blackA,

      // Learn Use Cases For Color Scale: https://www.radix-ui.com/docs/colors/palette-composition/understanding-the-scale#use-cases
    },
    fontSizes: {
      1: "12px",
      2: "13px",
      3: "15px",
      4: "17px",
      5: "19px",
      6: "21px",
      7: "27px",
      8: "35px",
      9: "59px",
    },
    fonts: {
      main: "'InterVariable'",
    },
    radii: {
      1: "4px",
      2: "6px",
      3: "8px",
      4: "12px",
      round: "50%",
      pill: "9999px",
    },
    sizes: {
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
      5: "25px",
      6: "35px",
      7: "45px",
      8: "65px",
      9: "80px",
      header: "$8",
    },
    space: {
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
      5: "25px",
      6: "35px",
      7: "45px",
      8: "65px",
      9: "80px",
    },
    transitions: {
      sidebar: "width 225ms ease",
      fadeIn: "opacity 0.3s ease, visibility 0.3s ease",
    },
    zIndices: {
      1: "100",
      2: "200",
      3: "300",
      4: "400",
      max: "999",
    },
  },
  media: {
    bp1: "(min-width: 425px)",
    bp2: "(min-width: 768px)",
    bp3: "(min-width: 1024px)",
    bp4: "(min-width: 1440px)",
    motion: "(prefers-reduced-motion)",
    hover: "(any-hover: hover)",
    dark: "(prefers-color-scheme: dark)",
    light: "(prefers-color-scheme: light)",
  },
  utils: {
    p: (value: PropertyValue<"padding">) => ({
      padding: value,
    }),
    pt: (value: PropertyValue<"paddingTop">) => ({
      paddingTop: value,
    }),
    pr: (value: PropertyValue<"paddingRight">) => ({
      paddingRight: value,
    }),
    pb: (value: PropertyValue<"paddingBottom">) => ({
      paddingBottom: value,
    }),
    pl: (value: PropertyValue<"paddingLeft">) => ({
      paddingLeft: value,
    }),
    px: (value: PropertyValue<"paddingLeft">) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    py: (value: PropertyValue<"paddingTop">) => ({
      paddingTop: value,
      paddingBottom: value,
    }),

    m: (value: PropertyValue<"margin">) => ({
      margin: value,
    }),
    mt: (value: PropertyValue<"marginTop">) => ({
      marginTop: value,
    }),
    mr: (value: PropertyValue<"marginRight">) => ({
      marginRight: value,
    }),
    mb: (value: PropertyValue<"marginBottom">) => ({
      marginBottom: value,
    }),
    ml: (value: PropertyValue<"marginLeft">) => ({
      marginLeft: value,
    }),
    mx: (value: PropertyValue<"marginLeft">) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: PropertyValue<"marginTop">) => ({
      marginTop: value,
      marginBottom: value,
    }),

    ta: (value: PropertyValue<"textAlign">) => ({
      textAlign: value,
    }),

    fd: (value: PropertyValue<"flexDirection">) => ({
      flexDirection: value,
    }),
    fw: (value: PropertyValue<"flexWrap">) => ({ flexWrap: value }),

    ai: (value: PropertyValue<"alignItems">) => ({
      alignItems: value,
    }),
    ac: (value: PropertyValue<"alignContent">) => ({
      alignContent: value,
    }),
    jc: (value: PropertyValue<"justifyContent">) => ({
      justifyContent: value,
    }),
    as: (value: PropertyValue<"alignSelf">) => ({
      alignSelf: value,
    }),
    fg: (value: PropertyValue<"flexGrow">) => ({ flexGrow: value }),
    fs: (value: PropertyValue<"flexShrink">) => ({
      flexShrink: value,
    }),
    fb: (value: PropertyValue<"flexBasis">) => ({
      flexBasis: value,
    }),

    bc: (value: PropertyValue<"backgroundColor">) => ({
      backgroundColor: value,
    }),

    br: (value: PropertyValue<"borderRadius">) => ({
      borderRadius: value,
    }),
    btrr: (value: PropertyValue<"borderTopRightRadius">) => ({
      borderTopRightRadius: value,
    }),
    bbrr: (value: PropertyValue<"borderBottomRightRadius">) => ({
      borderBottomRightRadius: value,
    }),
    bblr: (value: PropertyValue<"borderBottomLeftRadius">) => ({
      borderBottomLeftRadius: value,
    }),
    btlr: (value: PropertyValue<"borderTopLeftRadius">) => ({
      borderTopLeftRadius: value,
    }),

    bs: (value: PropertyValue<"boxShadow">) => ({
      boxShadow: value,
    }),

    lh: (value: PropertyValue<"lineHeight">) => ({
      lineHeight: value,
    }),

    ox: (value: PropertyValue<"overflowX">) => ({
      overflowX: value,
    }),
    oy: (value: PropertyValue<"overflowY">) => ({
      overflowY: value,
    }),

    pe: (value: PropertyValue<"pointerEvents">) => ({
      pointerEvents: value,
    }),
    us: (value: PropertyValue<"userSelect">) => ({
      WebkitUserSelect: value,
      userSelect: value,
    }),

    userSelect: (value: PropertyValue<"userSelect">) => ({
      WebkitUserSelect: value,
      userSelect: value,
    }),

    size: (value: PropertyValue<"width">) => ({
      width: value,
      height: value,
    }),

    appearance: (value: PropertyValue<"appearance">) => ({
      WebkitAppearance: value,
      appearance: value,
    }),
    backgroundClip: (value: PropertyValue<"backgroundClip">) => ({
      WebkitBackgroundClip: value,
      backgroundClip: value,
    }),
  },
});

export type CSS = StitchesCSS<typeof config>;

export const darkTheme = createTheme("dark-theme", {
  colors: {
    primary1: greenDark.green1,
    primary2: greenDark.green2,
    primary3: greenDark.green3,
    primary4: greenDark.green4,
    primary5: greenDark.green5,
    primary6: greenDark.green6,
    primary7: greenDark.green7,
    primary8: greenDark.green8,
    primary9: greenDark.green9,
    primary10: greenDark.green10,
    primary11: greenDark.green11,
    primary12: greenDark.green12,

    primaryA1: greenDarkA.greenA1,
    primaryA2: greenDarkA.greenA2,
    primaryA3: greenDarkA.greenA3,
    primaryA4: greenDarkA.greenA4,
    primaryA5: greenDarkA.greenA5,
    primaryA6: greenDarkA.greenA6,
    primaryA7: greenDarkA.greenA7,
    primaryA8: greenDarkA.greenA8,
    primaryA9: greenDarkA.greenA9,
    primaryA10: greenDarkA.greenA10,
    primaryA11: greenDarkA.greenA11,
    primaryA12: greenDarkA.greenA12,

    secondary1: blueDark.blue1,
    secondary2: blueDark.blue2,
    secondary3: blueDark.blue3,
    secondary4: blueDark.blue4,
    secondary5: blueDark.blue5,
    secondary6: blueDark.blue6,
    secondary7: blueDark.blue7,
    secondary8: blueDark.blue8,
    secondary9: blueDark.blue9,
    secondary10: blueDark.blue10,
    secondary11: blueDark.blue11,
    secondary12: blueDark.blue12,

    secondaryA1: blueDarkA.blueA1,
    secondaryA2: blueDarkA.blueA2,
    secondaryA3: blueDarkA.blueA3,
    secondaryA4: blueDarkA.blueA4,
    secondaryA5: blueDarkA.blueA5,
    secondaryA6: blueDarkA.blueA6,
    secondaryA7: blueDarkA.blueA7,
    secondaryA8: blueDarkA.blueA8,
    secondaryA9: blueDarkA.blueA9,
    secondaryA10: blueDarkA.blueA10,
    secondaryA11: blueDarkA.blueA11,
    secondaryA12: blueDarkA.blueA12,

    gray1: sageDark.sage1,
    gray2: sageDark.sage2,
    gray3: sageDark.sage3,
    gray4: sageDark.sage4,
    gray5: sageDark.sage5,
    gray6: sageDark.sage6,
    gray7: sageDark.sage7,
    gray8: sageDark.sage8,
    gray9: sageDark.sage9,
    gray10: sageDark.sage10,
    gray11: sageDark.sage11,
    gray12: sageDark.sage12,

    grayA1: sageDarkA.sageA1,
    grayA2: sageDarkA.sageA2,
    grayA3: sageDarkA.sageA3,
    grayA4: sageDarkA.sageA4,
    grayA5: sageDarkA.sageA5,
    grayA6: sageDarkA.sageA6,
    grayA7: sageDarkA.sageA7,
    grayA8: sageDarkA.sageA8,
    grayA9: sageDarkA.sageA9,
    grayA10: sageDarkA.sageA10,
    grayA11: sageDarkA.sageA11,
    grayA12: sageDarkA.sageA12,

    success1: greenDark.green1,
    success2: greenDark.green2,
    success3: greenDark.green3,
    success4: greenDark.green4,
    success5: greenDark.green5,
    success6: greenDark.green6,
    success7: greenDark.green7,
    success8: greenDark.green8,
    success9: greenDark.green9,
    success10: greenDark.green10,
    success11: greenDark.green11,
    success12: greenDark.green12,

    successA1: greenDarkA.greenA1,
    successA2: greenDarkA.greenA2,
    successA3: greenDarkA.greenA3,
    successA4: greenDarkA.greenA4,
    successA5: greenDarkA.greenA5,
    successA6: greenDarkA.greenA6,
    successA7: greenDarkA.greenA7,
    successA8: greenDarkA.greenA8,
    successA9: greenDarkA.greenA9,
    successA10: greenDarkA.greenA10,
    successA11: greenDarkA.greenA11,
    successA12: greenDarkA.greenA12,

    info1: blueDark.blue1,
    info2: blueDark.blue2,
    info3: blueDark.blue3,
    info4: blueDark.blue4,
    info5: blueDark.blue5,
    info6: blueDark.blue6,
    info7: blueDark.blue7,
    info8: blueDark.blue8,
    info9: blueDark.blue9,
    info10: blueDark.blue10,
    info11: blueDark.blue11,
    info12: blueDark.blue12,

    infoA1: blueDarkA.blueA1,
    infoA2: blueDarkA.blueA2,
    infoA3: blueDarkA.blueA3,
    infoA4: blueDarkA.blueA4,
    infoA5: blueDarkA.blueA5,
    infoA6: blueDarkA.blueA6,
    infoA7: blueDarkA.blueA7,
    infoA8: blueDarkA.blueA8,
    infoA9: blueDarkA.blueA9,
    infoA10: blueDarkA.blueA10,
    infoA11: blueDarkA.blueA11,
    infoA12: blueDarkA.blueA12,

    warn1: yellowDark.yellow1,
    warn2: yellowDark.yellow2,
    warn3: yellowDark.yellow3,
    warn4: yellowDark.yellow4,
    warn5: yellowDark.yellow5,
    warn6: yellowDark.yellow6,
    warn7: yellowDark.yellow7,
    warn8: yellowDark.yellow8,
    warn9: yellowDark.yellow9,
    warn10: yellowDark.yellow10,
    warn11: yellowDark.yellow11,
    warn12: yellowDark.yellow12,

    warnA1: yellowDarkA.yellowA1,
    warnA2: yellowDarkA.yellowA2,
    warnA3: yellowDarkA.yellowA3,
    warnA4: yellowDarkA.yellowA4,
    warnA5: yellowDarkA.yellowA5,
    warnA6: yellowDarkA.yellowA6,
    warnA7: yellowDarkA.yellowA7,
    warnA8: yellowDarkA.yellowA8,
    warnA9: yellowDarkA.yellowA9,
    warnA10: yellowDarkA.yellowA10,
    warnA11: yellowDarkA.yellowA11,
    warnA12: yellowDarkA.yellowA12,

    error1: redDark.red1,
    error2: redDark.red2,
    error3: redDark.red3,
    error4: redDark.red4,
    error5: redDark.red5,
    error6: redDark.red6,
    error7: redDark.red7,
    error8: redDark.red8,
    error9: redDark.red9,
    error10: redDark.red10,
    error11: redDark.red11,
    error12: redDark.red12,

    errorA1: redDarkA.redA1,
    errorA2: redDarkA.redA2,
    errorA3: redDarkA.redA3,
    errorA4: redDarkA.redA4,
    errorA5: redDarkA.redA5,
    errorA6: redDarkA.redA6,
    errorA7: redDarkA.redA7,
    errorA8: redDarkA.redA8,
    errorA9: redDarkA.redA9,
    errorA10: redDarkA.redA10,
    errorA11: redDarkA.redA11,
    errorA12: redDarkA.redA12,
  },
});

export const globalStyles = globalCss({
  // https://www.joshwcomeau.com/css/custom-css-reset/
  "*, *::before, *::after": {
    boxSizing: "border-box",
  },
  "*": {
    margin: 0,
    fontFamily: "$main",
  },
  "html, body": {
    height: "100%",
  },
  body: {
    lineHeight: 1.5,
    fontSmooth: "antialiased",
  },
  "img, picture, video, canvas, svg, iframe": {
    display: "block",
    maxWidth: "100%",
  },
  "p, h1, h2, h3, h4, h5, h6": {
    overflowWrap: "break-word",
  },
  "#root, #__next": {
    isolation: "isolate",
  },
});
